title: Imtiaz Notes
description: Â© Copyright 2024 https://imtiazkhands.github.io/notes
remote_theme: "jeffreytse/jekyll-theme-yat"
theme: jekyll-theme-yat

plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-toc
relative_links:
  enabled: true
  collections: true


# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: coderay  
