title: Imtiaz Notes
description: Â© Copyright 2024 https://imtiazkhands.github.io/notes
theme: cayman

# Other Jekyll configuration options

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
